version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: ${POSTGRES_HOST_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - stocks-app-network
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_stock_app
    hostname: ${APP_HOST_NAME}
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - stocks-app-network

networks:
  stocks-app-network:
    driver: bridge
volumes:
  postgres-data:
